version: 0.2

phases:
  build:
    commands:
      - echo "Copying Reach Application files to artifact directory..."
      - mkdir -p artifacts
      - rsync -av --exclude='artifacts' ./ artifacts/


artifacts:
  files:
    - '**/*'
  base-directory: artifacts
  discard-paths: no
